import {
  Database,
  KeyRound,
  Network,
  Router,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react"

export type ConsoleLocale = "zh" | "en"
export type ConsoleRouteKey = "overview" | "nodes" | "access" | "network" | "audit"

export const CONSOLE_NAV_ITEMS: Array<{
  key: ConsoleRouteKey
  href: string
  icon: LucideIcon
}> = [
  { key: "overview", href: "/overview/", icon: Database },
  { key: "nodes", href: "/nodes/", icon: Router },
  { key: "access", href: "/access/", icon: KeyRound },
  { key: "network", href: "/network/", icon: Network },
  { key: "audit", href: "/audit/", icon: ShieldCheck },
]

export const CONSOLE_COPY = {
  zh: {
    appName: "管理控制台",
    projectTagline: "Rust 自托管控制面",
    independenceNotice:
      "独立项目，兼容 Tailscale 客户端；与 Tailscale Inc. 及 headscale 项目无关联。",
    breadcrumbRoot: "控制台",
    refresh: "刷新",
    refreshing: "刷新中",
    connection: "连接",
    currentOrigin: "当前站点",
    customOrigin: "自定义地址",
    lastSync: "最近同步",
    timezone: "时区",
    signOut: "退出",
    sameOrigin: "当前站点同源",
    customApi: "自定义",
    backToOrigin: "改回同源",
    token: "Token",
    api: "API",
    themeDark: "深色",
    themeLight: "浅色",
    timezoneLocal: "本地",
    timezoneUtc: "UTC",
    localeToggle: "EN",
    commandPalette: "命令面板",
    commandPaletteHint: "⌘K",
    errorUnknown: "未知错误",
    errors: {
      missingApiBaseUrl: "缺少管理 API 地址。",
      missingAdminToken: "缺少管理员 token。",
      networkError: "网络请求失败，请检查控制面地址与网络连接。",
      requestTimeout: "请求超时，请稍后重试。",
      requestFailed: (status: number) => `请求失败（${status}）。`,
    },
    loginTitle: "控制台登录",
    loginSubtitle: "输入管理员 token 进入控制台。",
    loginSubmit: "进入控制台",
    loginSuccess: "已连接到控制台。",
    sessionExpired: "登录已失效，请重新输入管理员 token。",
    nav: {
      overview: "总览",
      nodes: "节点",
      access: "接入",
      network: "网络",
      audit: "审计",
    },
    page: {
      overview: {
        title: "控制面状态",
        subtitle: "健康、配置、DERP、运行面板",
      },
      nodes: {
        title: "节点管理",
        subtitle: "节点清单、在线状态、禁用操作",
      },
      access: {
        title: "认证与签发",
        subtitle: "Auth Key 签发、回收与复制",
      },
      network: {
        title: "路由与 DERP",
        subtitle: "审批队列、DERP 刷新、网络信号",
      },
      audit: {
        title: "审计事件",
        subtitle: "最近变更与操作记录",
      },
    },
    common: {
      ok: "正常",
      yes: "是",
      no: "否",
      loading: "加载中",
      loadFailed: "加载失败",
      retry: "重试",
      confirm: "确认",
      cancel: "取消",
      dismiss: "关闭",
      details: "详情",
      viewDetails: "查看详情",
      focusSearch: "聚焦当前页搜索",
      clear: "清除",
      copyLink: "复制链接",
      linkCopied: "已复制当前链接。",
      linkCopyFailed: "复制链接失败。",
      clearSelection: "取消选择",
      clearFilters: "清空筛选",
      columns: "列",
      density: "密度",
      comfortable: "舒适",
      compact: "紧凑",
      rowsPerPage: "每页条数",
      previous: "上一页",
      next: "下一页",
      page: (current: number, total: number) => `第 ${current} / ${total} 页`,
      range: (from: number, to: number, total: number) => `${from}-${to} / ${total}`,
      show: "显示",
      hide: "隐藏",
      never: "无",
      enabled: "启用",
      disabled: "关闭",
      configured: "已配置",
      unconfigured: "未配置",
      none: "空",
      notSet: "未设置",
      identifier: "标识",
      hostname: "主机名",
      stableId: "稳定 ID",
      ipv4: "IPv4",
      ipv6: "IPv6",
      lastSeen: "最近活跃",
      createdAt: "创建时间",
      expiresAt: "过期时间",
      lastUsed: "最近使用",
      reusable: "可复用",
      ephemeral: "临时节点",
      usage: "使用次数",
      approval: "审批",
      advertised: "广播",
      routeType: "路由类型",
      actor: "操作者",
      mechanism: "机制",
      target: "目标",
      occurredAt: "发生时间",
      processing: "处理中",
      copy: "复制",
      copied: "已复制",
      noIpv4: "无 IPv4",
      noIpv6: "无 IPv6",
      seconds: "秒",
      localTime: "本地时间",
      utcTime: "UTC",
    },
    commands: {
      title: "快速操作",
      placeholder: "搜索页面或操作",
      empty: "没有匹配的结果。",
      groups: {
        navigate: "导航",
        actions: "操作",
      },
      actions: {
        overview: "前往总览",
        nodes: "前往节点",
        access: "前往接入",
        network: "前往网络",
        audit: "前往审计",
        refresh: "刷新当前控制台",
        theme: "切换主题",
        locale: "切换语言",
        timezone: "切换时区",
        signOut: "退出登录",
      },
    },
    status: {
      node: {
        online: "在线",
        offline: "离线",
        pending: "待注册",
        expired: "已过期",
        disabled: "已停用",
      },
      tagSource: {
        none: "无标签源",
        request: "客户端请求",
        auth_key: "Auth Key",
        admin: "管理员强制",
      },
      authKey: {
        active: "可用",
        revoked: "已撤销",
        expired: "已过期",
      },
      routeApproval: {
        approved: "已批准",
        rejected: "已拒绝",
        pending: "待审批",
      },
    },
    overview: {
      metrics: {
        online: "在线节点",
        config: "配置状态",
        derp: "DERP 区域",
        warnings: "配置告警",
        uptime: "运行时长",
      },
      panels: {
        healthTitle: "服务与健康",
        healthEyebrow: "运行时",
        controlTitle: "控制与网络",
        controlEyebrow: "控制面",
        derpTitle: "DERP 运行时",
        derpEyebrow: "中继",
        doctorTitle: "配置诊断",
        doctorEyebrow: "调试",
      },
      health: {
        service: "服务",
        version: "版本",
        bind: "监听",
        log: "日志",
        uptime: "运行时长",
        configWarnings: "配置告警",
        present: "存在",
        absent: "无",
      },
      control: {
        tailnetIpv4: "IPv4 Tailnet",
        tailnetIpv6: "IPv6 Tailnet",
        controlProtocol: "控制协议",
        adminAuth: "管理鉴权",
        webRoot: "静态前端",
        stun: "STUN",
      },
      derp: {
        regions: "区域",
        sources: "来源",
        failures: "失败",
        regionSummary: (regionCode: string, nodeCount: number) =>
          `${regionCode} · ${nodeCount} 个节点`,
      },
    },
    nodes: {
      panelTitle: "节点清单",
      panelEyebrow: "库存",
      tableTitle: "节点清单",
      detailsTitle: "节点详情",
      count: (shown: number, total: number) => `${shown} / ${total} 个节点显示中`,
      columns: {
        node: "节点",
        status: "状态",
        tailAddress: "Tail 地址",
        tags: "标签",
        lastSeen: "最近活跃",
      },
      filterPlaceholder: "按节点名、主机名、IP 或标签筛选",
      empty: "当前没有可显示的节点。",
      disable: "停用",
      disabling: "处理中",
      bulkDisable: "批量停用",
      selectedCount: (count: number) => `已选择 ${count} 个节点`,
      disableConfirm: (name: string) => `确定停用节点“${name}”吗？`,
      bulkDisableConfirm: (count: number) => `确定停用已选择的 ${count} 个节点吗？`,
      disableSuccess: (name: string) => `节点“${name}”已停用。`,
      bulkDisableSuccess: (success: number, failed: number) =>
        failed > 0
          ? `已停用 ${success} 个节点，${failed} 个失败。`
          : `已停用 ${success} 个节点。`,
    },
    access: {
      issueTitle: "签发 Auth Key",
      issueEyebrow: "签发",
      authKeysTitle: "Auth Keys",
      authKeysEyebrow: "接入",
      detailsTitle: "Auth Key 详情",
      latestTitle: "最近签发",
      latestEyebrow: "最新",
      latestEmpty: "空",
      form: {
        description: "描述",
        descriptionPlaceholder: "android-sidecar",
        tags: "标签",
        tagsPlaceholder: "tag:prod, tag:nginx",
        reusable: "允许复用",
        ephemeral: "临时节点",
        issue: "签发",
        issuing: "签发中",
      },
      loading: "正在加载 Auth Key 列表",
      revokeConfirm: (label: string) => `确定撤销 Auth Key“${label}”吗？`,
      copyFailed: "复制失败，请手动复制。",
      revokeSuccess: (label: string) => `Auth Key“${label}”已撤销。`,
      issueSuccess: "Auth Key 已签发。",
      bulkRevoke: "批量撤销",
      selectedCount: (count: number) => `已选择 ${count} 个密钥`,
      bulkRevokeConfirm: (count: number) => `确定撤销已选择的 ${count} 个 Auth Key 吗？`,
      bulkRevokeSuccess: (success: number, failed: number) =>
        failed > 0
          ? `已撤销 ${success} 个 Auth Key，${failed} 个失败。`
          : `已撤销 ${success} 个 Auth Key。`,
      table: {
        title: "Auth Key 库",
        count: (shown: number, total: number) => `${shown} / ${total} 个密钥显示中`,
        columns: {
          key: "密钥",
          status: "状态",
          tags: "标签",
          policy: "策略",
          usage: "使用",
          lifecycle: "生命周期",
        },
        descriptionFallback: "未命名 Auth Key",
        reusable: "可复用",
        oneTime: "一次性",
        ephemeral: "临时节点",
        persistent: "持久节点",
        usageCount: (count: number) => `${count} 次`,
        createdAt: (value: string) => `创建于 ${value}`,
        expiresAt: (value: string) => `到期于 ${value}`,
        filterPlaceholder: "按描述、ID 或标签筛选",
        empty: "当前没有可显示的 Auth Key。",
        revoke: "撤销",
        revoking: "处理中",
      },
    },
    network: {
      routesTitle: "路由审批",
      routesEyebrow: "路由",
      detailsTitle: "路由详情",
      signalsTitle: "网络信号",
      signalsEyebrow: "信号",
      derpRefreshTitle: "DERP 刷新",
      derpRefreshEyebrow: "运行时",
      metrics: {
        pending: "待审批",
        derpFailures: "DERP 失败",
      },
      refresh: {
        lastSuccess: "最近成功",
        lastAttempt: "最近尝试",
        interval: "刷新间隔",
        externalSources: "外部源",
        seconds: (value: number) => `${value} 秒`,
      },
      table: {
        title: "路由审批",
        count: (shown: number, total: number) => `${shown} / ${total} 条路由显示中`,
        columns: {
          prefix: "路由前缀",
          approval: "审批",
          intent: "意图",
          source: "来源",
        },
        nodeLabel: (name: string) => `节点 ${name}`,
        advertised: "已广播",
        notAdvertised: "未广播",
        exitNode: "出口节点",
        subnetRoute: "子网路由",
        autoApproved: "策略自动批准",
        awaitingDecision: "等待人工决策",
        filterPlaceholder: "按前缀或节点名筛选",
        empty: "当前没有可显示的路由。",
        approve: "批准",
        approving: "处理中",
        reject: "拒绝",
        rejecting: "处理中",
        approveConfirm: (prefix: string) => `确定批准路由“${prefix}”吗？`,
        rejectConfirm: (prefix: string) => `确定拒绝路由“${prefix}”吗？`,
        approveSuccess: (prefix: string) => `路由“${prefix}”已批准。`,
        rejectSuccess: (prefix: string) => `路由“${prefix}”已拒绝。`,
        selectedCount: (count: number) => `已选择 ${count} 条路由`,
        bulkApprove: "批量批准",
        bulkReject: "批量拒绝",
        bulkApproveConfirm: (count: number) => `确定批准已选择的 ${count} 条路由吗？`,
        bulkRejectConfirm: (count: number) => `确定拒绝已选择的 ${count} 条路由吗？`,
        bulkApproveSuccess: (success: number, failed: number) =>
          failed > 0 ? `已批准 ${success} 条路由，${failed} 条失败。` : `已批准 ${success} 条路由。`,
        bulkRejectSuccess: (success: number, failed: number) =>
          failed > 0 ? `已拒绝 ${success} 条路由，${failed} 条失败。` : `已拒绝 ${success} 条路由。`,
      },
    },
    audit: {
      title: "审计事件",
      eyebrow: "事件",
      detailsTitle: "事件详情",
      loading: "正在加载审计事件",
      empty: "空",
      filterPlaceholder: "按目标、操作者或机制筛选",
      kindLabel: "事件类型",
      allKinds: "全部类型",
      count: (shown: number, total: number) => `${shown} / ${total} 条事件显示中`,
      kindNames: {
        node_registered: "节点注册",
        node_updated: "节点更新",
        node_disabled: "节点停用",
        node_deleted: "节点删除",
        auth_key_created: "Auth Key 创建",
        auth_key_revoked: "Auth Key 撤销",
        policy_updated: "策略更新",
        dns_updated: "DNS 更新",
        route_created: "路由创建",
        route_approved: "路由批准",
        route_rejected: "路由拒绝",
        admin_authenticated: "管理员认证",
        backup_restored: "备份恢复",
        ssh_check_approved: "SSH 审批通过",
        ssh_check_rejected: "SSH 审批拒绝",
      },
      actorSeparator: " · ",
    },
  },
  en: {
    appName: "Admin Console",
    projectTagline: "Self-hosted Rust control plane",
    independenceNotice:
      "Independent project compatible with Tailscale clients; not affiliated with Tailscale Inc. or the headscale project.",
    breadcrumbRoot: "Console",
    refresh: "Refresh",
    refreshing: "Refreshing",
    connection: "Connection",
    currentOrigin: "Current origin",
    customOrigin: "Custom API",
    lastSync: "Last sync",
    timezone: "Timezone",
    signOut: "Sign out",
    sameOrigin: "Current origin",
    customApi: "Custom",
    backToOrigin: "Use origin",
    token: "Token",
    api: "API",
    themeDark: "Dark",
    themeLight: "Light",
    timezoneLocal: "Local",
    timezoneUtc: "UTC",
    localeToggle: "中文",
    commandPalette: "Command Menu",
    commandPaletteHint: "⌘K",
    errorUnknown: "Unknown error",
    errors: {
      missingApiBaseUrl: "Missing admin API base URL.",
      missingAdminToken: "Missing administrator token.",
      networkError: "Network request failed. Check the control plane address and connectivity.",
      requestTimeout: "The request timed out. Please try again.",
      requestFailed: (status: number) => `Request failed (${status}).`,
    },
    loginTitle: "Console Login",
    loginSubtitle: "Enter the admin token to access the console.",
    loginSubmit: "Enter Console",
    loginSuccess: "Connected to the console.",
    sessionExpired: "Session expired. Enter the admin token again.",
    nav: {
      overview: "Overview",
      nodes: "Nodes",
      access: "Access",
      network: "Network",
      audit: "Audit",
    },
    page: {
      overview: {
        title: "Control Plane Status",
        subtitle: "Health, config, DERP and runtime panels",
      },
      nodes: {
        title: "Node Management",
        subtitle: "Inventory, status and disable actions",
      },
      access: {
        title: "Auth & Issuance",
        subtitle: "Issue, revoke and copy auth keys",
      },
      network: {
        title: "Routes & DERP",
        subtitle: "Approvals, refresh status and network signals",
      },
      audit: {
        title: "Audit Events",
        subtitle: "Recent mutations and operator actions",
      },
    },
    common: {
      ok: "OK",
      yes: "Yes",
      no: "No",
      loading: "Loading",
      loadFailed: "Failed to load",
      retry: "Retry",
      confirm: "Confirm",
      cancel: "Cancel",
      dismiss: "Dismiss",
      details: "Details",
      viewDetails: "View details",
      focusSearch: "Focus page search",
      clear: "Clear",
      copyLink: "Copy link",
      linkCopied: "Current link copied.",
      linkCopyFailed: "Failed to copy link.",
      clearSelection: "Clear selection",
      clearFilters: "Clear filters",
      columns: "Columns",
      density: "Density",
      comfortable: "Comfortable",
      compact: "Compact",
      rowsPerPage: "Rows per page",
      previous: "Previous",
      next: "Next",
      page: (current: number, total: number) => `Page ${current} / ${total}`,
      range: (from: number, to: number, total: number) => `${from}-${to} of ${total}`,
      show: "Show",
      hide: "Hide",
      never: "Never",
      enabled: "Enabled",
      disabled: "Disabled",
      configured: "Configured",
      unconfigured: "Not configured",
      none: "Empty",
      notSet: "Not set",
      identifier: "Identifier",
      hostname: "Hostname",
      stableId: "Stable ID",
      ipv4: "IPv4",
      ipv6: "IPv6",
      lastSeen: "Last seen",
      createdAt: "Created at",
      expiresAt: "Expires at",
      lastUsed: "Last used",
      reusable: "Reusable",
      ephemeral: "Ephemeral",
      usage: "Usage",
      approval: "Approval",
      advertised: "Advertised",
      routeType: "Route type",
      actor: "Actor",
      mechanism: "Mechanism",
      target: "Target",
      occurredAt: "Occurred at",
      processing: "Processing",
      copy: "Copy",
      copied: "Copied",
      noIpv4: "No IPv4",
      noIpv6: "No IPv6",
      seconds: "s",
      localTime: "Local time",
      utcTime: "UTC",
    },
    commands: {
      title: "Quick Actions",
      placeholder: "Search pages or actions",
      empty: "No matching actions.",
      groups: {
        navigate: "Navigate",
        actions: "Actions",
      },
      actions: {
        overview: "Go to overview",
        nodes: "Go to nodes",
        access: "Go to access",
        network: "Go to network",
        audit: "Go to audit",
        refresh: "Refresh console",
        theme: "Toggle theme",
        locale: "Switch language",
        timezone: "Switch timezone",
        signOut: "Sign out",
      },
    },
    status: {
      node: {
        online: "Online",
        offline: "Offline",
        pending: "Pending",
        expired: "Expired",
        disabled: "Disabled",
      },
      tagSource: {
        none: "No tag source",
        request: "Client request",
        auth_key: "Auth key",
        admin: "Admin enforced",
      },
      authKey: {
        active: "Active",
        revoked: "Revoked",
        expired: "Expired",
      },
      routeApproval: {
        approved: "Approved",
        rejected: "Rejected",
        pending: "Pending",
      },
    },
    overview: {
      metrics: {
        online: "Online nodes",
        config: "Config",
        derp: "DERP regions",
        warnings: "Warnings",
        uptime: "Uptime",
      },
      panels: {
        healthTitle: "Service & Health",
        healthEyebrow: "Runtime",
        controlTitle: "Control & Network",
        controlEyebrow: "Control plane",
        derpTitle: "DERP Runtime",
        derpEyebrow: "Relay",
        doctorTitle: "Config Doctor",
        doctorEyebrow: "Debug",
      },
      health: {
        service: "Service",
        version: "Version",
        bind: "Bind",
        log: "Log",
        uptime: "Uptime",
        configWarnings: "Config warnings",
        present: "Present",
        absent: "None",
      },
      control: {
        tailnetIpv4: "IPv4 tailnet",
        tailnetIpv6: "IPv6 tailnet",
        controlProtocol: "Control protocol",
        adminAuth: "Admin auth",
        webRoot: "Static frontend",
        stun: "STUN",
      },
      derp: {
        regions: "Regions",
        sources: "Sources",
        failures: "Failures",
        regionSummary: (regionCode: string, nodeCount: number) =>
          `${regionCode} · ${nodeCount} node${nodeCount === 1 ? "" : "s"}`,
      },
    },
    nodes: {
      panelTitle: "Node Inventory",
      panelEyebrow: "Inventory",
      tableTitle: "Nodes",
      detailsTitle: "Node details",
      count: (shown: number, total: number) => `Showing ${shown} / ${total} nodes`,
      columns: {
        node: "Node",
        status: "Status",
        tailAddress: "Tail addresses",
        tags: "Tags",
        lastSeen: "Last seen",
      },
      filterPlaceholder: "Filter by node name, hostname, IP or tags",
      empty: "No nodes available.",
      disable: "Disable",
      disabling: "Processing",
      bulkDisable: "Disable selected",
      selectedCount: (count: number) => `${count} node${count === 1 ? "" : "s"} selected`,
      disableConfirm: (name: string) => `Disable node "${name}"?`,
      bulkDisableConfirm: (count: number) =>
        `Disable the ${count} selected node${count === 1 ? "" : "s"}?`,
      disableSuccess: (name: string) => `Node "${name}" has been disabled.`,
      bulkDisableSuccess: (success: number, failed: number) =>
        failed > 0
          ? `Disabled ${success} node${success === 1 ? "" : "s"} with ${failed} failure${failed === 1 ? "" : "s"}.`
          : `Disabled ${success} node${success === 1 ? "" : "s"}.`,
    },
    access: {
      issueTitle: "Issue Auth Key",
      issueEyebrow: "Issue",
      authKeysTitle: "Auth Keys",
      authKeysEyebrow: "Access",
      detailsTitle: "Auth Key details",
      latestTitle: "Latest Issued",
      latestEyebrow: "Latest",
      latestEmpty: "Empty",
      form: {
        description: "Description",
        descriptionPlaceholder: "android-sidecar",
        tags: "Tags",
        tagsPlaceholder: "tag:prod, tag:nginx",
        reusable: "Reusable",
        ephemeral: "Ephemeral node",
        issue: "Issue",
        issuing: "Issuing",
      },
      loading: "Loading auth keys",
      revokeConfirm: (label: string) => `Revoke auth key "${label}"?`,
      copyFailed: "Copy failed. Please copy it manually.",
      revokeSuccess: (label: string) => `Auth key "${label}" has been revoked.`,
      issueSuccess: "Auth key issued.",
      bulkRevoke: "Revoke selected",
      selectedCount: (count: number) => `${count} key${count === 1 ? "" : "s"} selected`,
      bulkRevokeConfirm: (count: number) =>
        `Revoke the ${count} selected auth key${count === 1 ? "" : "s"}?`,
      bulkRevokeSuccess: (success: number, failed: number) =>
        failed > 0
          ? `Revoked ${success} auth key${success === 1 ? "" : "s"} with ${failed} failure${failed === 1 ? "" : "s"}.`
          : `Revoked ${success} auth key${success === 1 ? "" : "s"}.`,
      table: {
        title: "Auth Key Inventory",
        count: (shown: number, total: number) => `Showing ${shown} / ${total} keys`,
        columns: {
          key: "Key",
          status: "Status",
          tags: "Tags",
          policy: "Policy",
          usage: "Usage",
          lifecycle: "Lifecycle",
        },
        descriptionFallback: "Unnamed auth key",
        reusable: "Reusable",
        oneTime: "One-time",
        ephemeral: "Ephemeral node",
        persistent: "Persistent node",
        usageCount: (count: number) => `${count} use${count === 1 ? "" : "s"}`,
        createdAt: (value: string) => `Created ${value}`,
        expiresAt: (value: string) => `Expires ${value}`,
        filterPlaceholder: "Filter by description, ID or tags",
        empty: "No auth keys available.",
        revoke: "Revoke",
        revoking: "Processing",
      },
    },
    network: {
      routesTitle: "Route Approvals",
      routesEyebrow: "Routes",
      detailsTitle: "Route details",
      signalsTitle: "Network Signals",
      signalsEyebrow: "Signals",
      derpRefreshTitle: "DERP Refresh",
      derpRefreshEyebrow: "Runtime",
      metrics: {
        pending: "Pending",
        derpFailures: "DERP failures",
      },
      refresh: {
        lastSuccess: "Last success",
        lastAttempt: "Last attempt",
        interval: "Refresh interval",
        externalSources: "External sources",
        seconds: (value: number) => `${value}s`,
      },
      table: {
        title: "Route Approvals",
        count: (shown: number, total: number) => `Showing ${shown} / ${total} routes`,
        columns: {
          prefix: "Prefix",
          approval: "Approval",
          intent: "Intent",
          source: "Source",
        },
        nodeLabel: (name: string) => `Node ${name}`,
        advertised: "Advertised",
        notAdvertised: "Not advertised",
        exitNode: "Exit node",
        subnetRoute: "Subnet route",
        autoApproved: "Auto-approved by policy",
        awaitingDecision: "Awaiting manual review",
        filterPlaceholder: "Filter by prefix or node name",
        empty: "No routes available.",
        approve: "Approve",
        approving: "Processing",
        reject: "Reject",
        rejecting: "Processing",
        approveConfirm: (prefix: string) => `Approve route "${prefix}"?`,
        rejectConfirm: (prefix: string) => `Reject route "${prefix}"?`,
        approveSuccess: (prefix: string) => `Route "${prefix}" has been approved.`,
        rejectSuccess: (prefix: string) => `Route "${prefix}" has been rejected.`,
        selectedCount: (count: number) => `${count} route${count === 1 ? "" : "s"} selected`,
        bulkApprove: "Approve selected",
        bulkReject: "Reject selected",
        bulkApproveConfirm: (count: number) =>
          `Approve the ${count} selected route${count === 1 ? "" : "s"}?`,
        bulkRejectConfirm: (count: number) =>
          `Reject the ${count} selected route${count === 1 ? "" : "s"}?`,
        bulkApproveSuccess: (success: number, failed: number) =>
          failed > 0
            ? `Approved ${success} route${success === 1 ? "" : "s"} with ${failed} failure${failed === 1 ? "" : "s"}.`
            : `Approved ${success} route${success === 1 ? "" : "s"}.`,
        bulkRejectSuccess: (success: number, failed: number) =>
          failed > 0
            ? `Rejected ${success} route${success === 1 ? "" : "s"} with ${failed} failure${failed === 1 ? "" : "s"}.`
            : `Rejected ${success} route${success === 1 ? "" : "s"}.`,
      },
    },
    audit: {
      title: "Audit Events",
      eyebrow: "Events",
      detailsTitle: "Event details",
      loading: "Loading audit events",
      empty: "Empty",
      filterPlaceholder: "Filter by target, actor or mechanism",
      kindLabel: "Kind",
      allKinds: "All kinds",
      count: (shown: number, total: number) => `Showing ${shown} / ${total} events`,
      kindNames: {
        node_registered: "Node registered",
        node_updated: "Node updated",
        node_disabled: "Node disabled",
        node_deleted: "Node deleted",
        auth_key_created: "Auth key created",
        auth_key_revoked: "Auth key revoked",
        policy_updated: "Policy updated",
        dns_updated: "DNS updated",
        route_created: "Route created",
        route_approved: "Route approved",
        route_rejected: "Route rejected",
        admin_authenticated: "Admin authenticated",
        backup_restored: "Backup restored",
        ssh_check_approved: "SSH check approved",
        ssh_check_rejected: "SSH check rejected",
      },
      actorSeparator: " · ",
    },
  },
} as const

export type ConsoleCopy = (typeof CONSOLE_COPY)[ConsoleLocale]
